"""governance_ui_frontend_only_check

Revision ID: 56ebad099bce
Revises: 20260313_add_finance_brazil_tax_fields
Create Date: 2026-03-14 12:51:46.140921

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '56ebad099bce'
down_revision = '20260313_add_finance_brazil_tax_fields'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('finance_invoices', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_fin_invoice_tenant_company_due_date'))
        batch_op.drop_index(batch_op.f('ix_fin_invoice_tenant_company_status_issue'))
        batch_op.drop_index(batch_op.f('ix_fin_invoice_tenant_company_type_issue'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('finance_invoices', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_fin_invoice_tenant_company_type_issue'), ['tenant_id', 'company_id', 'invoice_type', 'issue_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_fin_invoice_tenant_company_status_issue'), ['tenant_id', 'company_id', 'status', 'issue_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_fin_invoice_tenant_company_due_date'), ['tenant_id', 'company_id', 'due_date'], unique=False)

    # ### end Alembic commands ###
