"""Add shared_link_uuid to ELearningCertificate

Revision ID: 6a05fa798085
Revises: 20260514_add_quiz_scoring_rules
Create Date: 2026-05-15 07:13:48.787135

"""
from alembic import op
import sqlalchemy as sa
import uuid


# revision identifiers, used by Alembic.
revision = '6a05fa798085'
down_revision = '20260514_add_quiz_scoring_rules'
branch_labels = None
depends_on = None


def upgrade():
    # Add column as nullable first
    with op.batch_alter_table('e_learning_certificates', schema=None) as batch_op:
        batch_op.add_column(sa.Column('shared_link_uuid', sa.String(length=36), nullable=True))
        batch_op.create_index(batch_op.f('ix_e_learning_certificates_shared_link_uuid'), ['shared_link_uuid'], unique=True)

    # Populate UUIDs for existing certificates
    connection = op.get_bind()
    result = connection.execute(sa.text('SELECT id FROM e_learning_certificates WHERE shared_link_uuid IS NULL'))
    for row in result:
        new_uuid = str(uuid.uuid4())
        connection.execute(sa.text('UPDATE e_learning_certificates SET shared_link_uuid = :uuid WHERE id = :id'),
                          {'uuid': new_uuid, 'id': row[0]})

    # Now make it NOT NULL
    with op.batch_alter_table('e_learning_certificates', schema=None) as batch_op:
        batch_op.alter_column('shared_link_uuid', nullable=False)


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('finance_gl_accounts', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.alter_column('sort_order',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('0'))

    with op.batch_alter_table('e_learning_student_files', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_e_learning_student_files_uploaded_by_user_id'))
        batch_op.drop_index(batch_op.f('ix_e_learning_student_files_module_id'))
        batch_op.drop_index(batch_op.f('ix_e_learning_student_files_lesson_id'))
        batch_op.create_index(batch_op.f('ix_student_files_user'), ['user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_student_files_module'), ['module_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_student_files_lesson'), ['lesson_id'], unique=False)

    with op.batch_alter_table('e_learning_certificates', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_e_learning_certificates_shared_link_uuid'))
        batch_op.drop_column('shared_link_uuid')

    # ### end Alembic commands ###
