"""create user table

Revision ID: 880c1112df41
Revises: 20260208_add_reports
Create Date: 2026-02-12 10:52:58.986018

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '880c1112df41'
down_revision = '20260208_add_reports'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('dashboards', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_dashboards_is_primary'), ['is_primary'], unique=False)

    with op.batch_alter_table('data_sources', schema=None) as batch_op:
        batch_op.add_column(sa.Column('base_url', sa.String(length=300), nullable=True))
        batch_op.add_column(sa.Column('method', sa.String(length=300), nullable=True))

    with op.batch_alter_table('etl_connections', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tenant_id', sa.Integer(), nullable=True))
        batch_op.create_index(batch_op.f('ix_etl_connections_tenant_id'), ['tenant_id'], unique=False)
        batch_op.create_foreign_key(None, 'tenants', ['tenant_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('etl_connections', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_etl_connections_tenant_id'))
        batch_op.drop_column('tenant_id')

    with op.batch_alter_table('data_sources', schema=None) as batch_op:
        batch_op.drop_column('method')
        batch_op.drop_column('base_url')

    with op.batch_alter_table('dashboards', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_dashboards_is_primary'))

    # ### end Alembic commands ###
